title: "APL STEM: Girl Power!"
description: STEM Workshop for Girl Power
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
collections:
  women:
    output: true
